#!/bin/sh
# This script is copied over to /etc/dhcp/dhclient-enter-hooks.d/ by `test_e2e.sh`.
# It's purpose is to prevent dhclient from overwriting global network configuration (especially DNS servers).
# It accomplishes this goal by exiting, which prevents other hooks from running.

if [ "$reason" = "REBOOT" -o "$reason" = "BOUND" ]; then
  # uncomment & run test to see available variables
  env
  ip addr add ${new_ip_address}/$new_subnet_mask broadcast $new_broadcast_address dev $interface
  ip route add default via $new_routers dev $interface
  ip link set $interface up
else
  # uncomment & run test to see available events
  # echo "Unknown reason: $reason"
  :
fi

exit 1
