name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16"
    - name: Symlink LLVMgold.so
      run: sudo ln -s LLVMgold.so /lib/x86_64-linux-gnu/LLVMgold.so
      working-directory: ${{ env.LLVM_PATH }}/lib
    - name: Install libncurses5 (Clang needs it), and libsystemd-dev
      run: sudo apt-get install -y libncurses5 libsystemd-dev
    - name: make gatekeeper
      run: make gatekeeper
    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
