name: End-to-end test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "17.0"
    - name: Update APT repositories
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt install -y valgrind inotify-tools
    - name: Run test
      run: ./run test_e2e
    # - name: Debug with tmate on failure
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3
